logging:
  file: e:\\demo\\demo.log
  level: info
server:
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.197.184/springboot?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
